services:
  redis:
    image: "redis"
    ports:
      - "6379:6379"
    command: redis-server --bind 0.0.0.0 --save '1 5'
    volumes:
    - '~/redisdata:/data:rw'
    networks:
            - development-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3        
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 2GB
        reservations:
          cpus: '0.25'
          memory: 256M  
  alvarasdash:
    build:
      context: .
    image: "stival/alvaradash:latest"
    ports:
      - "8051:8051"
    links:
      - redis
    depends_on:
      - "redis"
    volumes:
      #- '~/.aws/credentials:/root/.aws/credentials:ro'
      - '../dataset:/root/dataset/:ro'
    environment:
      CACHE_TYPE: redis
      CACHE_DIR: redis://redis:6379
      HOME_BUCKET: /root/dataset/
      #HOME_BUCKET: s3://cwbalvaras/
    networks:
            - development-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 2GB
        reservations:
          cpus: '0.25'
          memory: 256M  
networks:
    development-network:
        driver: bridge
volumes:
  redisdata: